Repository openshift/secondary-scheduler-operator, pull requests merged in 2022-07, with the labels that each got.

#55 bug 2100923: fix OwnerReference
  go.mod
  go.sum
  pkg/operator/target_config_reconciler.go
  vendor/github.com/openshift/library-go/pkg/controller/ownerref.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/modules.txt
Labels: bugzilla/valid-bug, approved, bugzilla/severity-low, lgtm

#56 bug 2102344: Set olm.skipRange to enable update path
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-high, bugzilla/valid-bug, approved, lgtm

#58 Sync 4.11
  go.mod
  go.sum
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
  pkg/operator/target_config_reconciler.go
  vendor/github.com/openshift/library-go/pkg/controller/ownerref.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/modules.txt
Labels: approved, lgtm

#59 bug 2105399: Force re-deployment when securitycontext fields are different
  pkg/operator/target_config_reconciler.go
Labels: bugzilla/valid-bug, approved, bugzilla/severity-medium, lgtm

#60 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm

#62 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm

#63 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm

#64 Update operators.openshift.io/valid-subscription
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#65 Update operators.openshift.io/valid-subscription
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#66 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm

#67 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm

#68 No-op change to trigger CPaaS mid-stream changes
  README.md
Labels: approved, lgtm
