Repository openshift/secondary-scheduler-operator, pull requests merged in 2024-09, with the labels that each got.

#167 no-jira: Add snyk secret to run sast-snyk-check job
  .tekton/secondary-scheduler-operator-pull-request.yaml
  .tekton/secondary-scheduler-operator-push.yaml
Labels: approved, lgtm, jira/valid-reference

#168 Update dev deploy manifests to render the latest secondary scheduler
  deploy/05_deployment.yaml
  deploy/06_configmap.yaml
  deploy/07_secondary-scheduler-operator.cr.yaml
Labels: approved, lgtm

#159 OCPBUGS-38317: scheduler-plugins change causes CrashLoopBackOff
  bindata/assets/secondary-scheduler/deployment.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#170 no-jira: CSV: provide a list of supported architectures
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#171 no-jira: Add bundle dockerfile for the operator
  bundle.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#177 WRKLDS-1470: Dockerfile: bump base image
  Dockerfile
Labels: approved, lgtm, jira/valid-reference

#178 WRKLDS-1470: [tekton]: build source image, hermetic build
  .tekton/secondary-scheduler-operator-bundle-pull-request.yaml
  .tekton/secondary-scheduler-operator-bundle-push.yaml
Labels: approved, lgtm, jira/valid-reference

#180 WRKLDS-1470: [bundle]: test component nudging
  bundle.Dockerfile
  hack/replace-image.sh
Labels: approved, lgtm, jira/valid-reference

#185 WRKLDS-1470: CSV: set related images
  bundle.Dockerfile
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#186 WRKLDS-1470: FBC for osso 1.4.0
  v4.18/catalog-template.json
  v4.18/catalog.Dockerfile
  v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
  v4.18/licenses/license.txt
Labels: approved, lgtm

#193 WRKLDS-1470: [tekton]: build source image, hermetic builds, extend the list of archs
  .tekton/secondary-scheduler-operator-pull-request.yaml
  .tekton/secondary-scheduler-operator-push.yaml
Labels: approved, lgtm, jira/valid-reference

#196 WRKLDS-1470: bundle.Dockerfile: point operator image to registry.redhat.io
  bundle.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#198 WRKLDS-1470: update fbc
  v4.18/catalog-template.json
  v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
Labels: approved, lgtm, jira/valid-reference

#199 WRKLDS-1470: update fbc
  v4.18/catalog-template.json
  v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
Labels: approved, lgtm, jira/valid-reference

#200 [bundle.Dockerfile]: set FROM to a pipiline test accepted base image
  bundle.Dockerfile
Labels: approved, lgtm

#207 no-jira: Prepare 1.3.2
  README.md
  bundle.Dockerfile
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-reference

#211 no-jira: Drop tekton config for master
  .tekton/secondary-scheduler-operator-bundle-pull-request.yaml
  .tekton/secondary-scheduler-operator-bundle-push.yaml
  .tekton/secondary-scheduler-operator-fbc-pull-request.yaml
  .tekton/secondary-scheduler-operator-fbc-push.yaml
  .tekton/secondary-scheduler-operator-pull-request.yaml
  .tekton/secondary-scheduler-operator-push.yaml
Labels: approved, lgtm, jira/valid-reference

#214 no-jira: [tekton]: build source image, hermetic builds, extend the list of archs
  .tekton/secondary-scheduler-operator-4-17-pull-request.yaml
  .tekton/secondary-scheduler-operator-4-17-push.yaml
Labels: approved, lgtm, jira/valid-reference

#217 no-jira: [tekton]: build source image, hermetic builds
  .tekton/secondary-scheduler-operator-bundle-4-17-pull-request.yaml
  .tekton/secondary-scheduler-operator-bundle-4-17-push.yaml
Labels: approved, lgtm, jira/valid-reference
