Repository openshift/secondary-scheduler-operator, pull requests merged in 2024-06, with the labels that each got.

#144 operand: fix containers[].securityContext.readOnlyRootFilesystem field name
  bindata/assets/secondary-scheduler/deployment.yaml
  deploy/05_deployment.yaml
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#145 WRKLDS-1142: operand: fix containers[].securityContext.readOnlyRootFilesystem field name
  bindata/assets/secondary-scheduler/deployment.yaml
  deploy/05_deployment.yaml
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-reference

#146 OCPBUGS-32976: Replace wildcards with an explicit list of verbs
  deploy/02_clusterrole.yaml
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/03_clusterrole.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#147 Operator deployment: set an emptyDir /tmp
  Dockerfile.metadata
  Dockerfile.rhel7
  deploy/05_deployment.yaml
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/05_deployment.yaml
Labels: approved, lgtm

#148 NO-JIRA: Operator deployment: set an emptyDir /tmp
  Dockerfile.metadata
  deploy/05_deployment.yaml
  manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
  test/e2e/bindata/assets/05_deployment.yaml
Labels: approved, lgtm, jira/valid-reference
